### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by deadfishhackers** [31ank/UltimateHentaiBot#7]
root@brunnyinc ~ **python3.6 Bot.py**
### Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 246, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 213, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Bot.py", line 140, in <module>
    bot.run('{}'.format(token))
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 571, in run
    return task.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 478, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 351, in login
    await self.http.static_login(token, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 250, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.

**Comment by 31ank** [comment]
error was a wrong placed token
